all:
  hosts:
    web1:
      ansible_host: 127.0.0.1
      ansible_user: deploy
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: /home/deploy/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
