name: CI/CD - Ansible Practice

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v4

      # 2️⃣ Instalar Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # 3️⃣ Verificar sintaxis del playbook
      - name: Ansible syntax check
        run: |
          ansible-playbook deploy.yml --syntax-check

      # 4️⃣ Simular el deploy (modo dry-run)
      - name: Simulate Deployment
        run: |
          ansible-playbook deploy.yml --check -i localhost, -c local
